export enum Config {
  PORT = 'PORT',
  JWT_SECRET = 'JWT_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION = 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_COOKIE_KEY = 'JWT_TOKEN_COOKIE_KEY',
  CORS_ORIGIN = 'CORS_ORIGIN',
}
